### ISSUE TITLE
Insert a new line

### ISSUE THREAD

**Issue by lucia1299** [paolobonora/DHDK-CC#2]
Add new line with your own name

**Comment by paolobonora** [comment]
We have to modify the indext.html file.
Insert a new <h3> tag at the end of the <body> contents.

**Comment by paolobonora** [comment]
@lucia1299 is my previous comment correct? We have to do that? Do I have to insert "my" name (="Paolo")?

**Comment by lucia1299** [comment]
@paolobonora yes thank you

**Comment by paolobonora** [comment]
@SpedicatiDaniele it is up to you now!

**Comment by paolobonora** [comment]
Daniele, have you entered the following line?
https://github.com/paolobonora/DHDK-CC/blob/e2c9512bbab309459f6831afd479e7b265b8b000/docs/index.html#L19

**Comment by SpedicatiDaniele** [comment]
Yes, I have done it
